In [1]:
!pip install numpy as np

ERROR: Could not find a version that satisfies the requirement as (from versions: none)
ERROR: No matching distribution found for as

[notice] A new release of pip is available: 24.1.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
!pip install --upgrade pip

  Using cached pip-24.2-py3-none-any.whl.metadata (3.6 kB)
Using cached pip-24.2-py3-none-any.whl (1.8 MB)


ERROR: To modify pip, please run the following command:
C:\Users\ADMIN\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 24.1.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np

In [19]:
data = [1,2,3,4]
array = np.array(data)
print(array)
print(type(array))

[1 2 3 4]
<class 'numpy.ndarray'>


In [9]:
l = list(array)
print(l)

[1, 2, 3, 4]


In [11]:
print(array.shape)

(4,)


In [12]:
print(array.dtype)

int32


In [16]:
print(array.ndim)

2


In [21]:
print(array[0])

1


In [20]:
print(array[0:3])

[1 2 3]


In [26]:
array_sum = array+2
print(array_sum)

[3 4 5 6]


In [25]:
array_prod = array*2
print(array_prod)

[2 4 6 8]


In [27]:
a = [[2,3,4,5],[2,6,5,4]]
array = np.array(a)

In [29]:
array_sum = np.sum(array)
print(array_sum)

31


In [30]:
array_sum = np.mean(array)
print(array_sum)

3.875


In [31]:
array_sum = np.min(array)
print(array_sum)

2


In [33]:
print(dir(array))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', 